param(
  [string]$RootDir = ".",
  [string]$Url = "http://localhost:4000",
  [int]$TimeoutSeconds = 45
)

$ErrorActionPreference = "SilentlyContinue"
$serverLog = Join-Path $env:TEMP "open890-server.log"
$diagnosticsOptInFile = Join-Path $RootDir "open890-diagnostics-optin.txt"
$githubIssueBaseUrl = "https://github.com/w9fyi/open890/issues/new"

function Test-Open890Ready {
  param([string]$Endpoint)
  try {
    $response = Invoke-WebRequest -UseBasicParsing -Uri $Endpoint -TimeoutSec 2
    return ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500)
  } catch {
    return $false
  }
}

function Get-LatestInstallerLogs {
  $pattern = Join-Path $env:TEMP "Setup Log*.txt"
  Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 3
}

function New-Open890DiagnosticsBundle {
  param([string]$FailureReason)

  $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $desktopDir = [Environment]::GetFolderPath("Desktop")
  if ([string]::IsNullOrWhiteSpace($desktopDir)) {
    $desktopDir = $env:TEMP
  }

  $bundleDir = Join-Path $env:TEMP "open890-diagnostics-$timestamp"
  $zipPath = Join-Path $desktopDir "open890-diagnostics-$timestamp.zip"
  New-Item -ItemType Directory -Path $bundleDir -Force | Out-Null

  $summaryPath = Join-Path $bundleDir "README.txt"
  @(
    "open890 Windows diagnostics bundle",
    "",
    "Failure reason: $FailureReason",
    "Timestamp: $(Get-Date -Format o)",
    "RootDir: $RootDir",
    "URL: $Url",
    "",
    "Attach this bundle to your GitHub issue."
  ) | Out-File -FilePath $summaryPath -Encoding UTF8

  if (Test-Path $serverLog) {
    Copy-Item -Path $serverLog -Destination (Join-Path $bundleDir "open890-server.log") -Force
  }

  $pidCheckLog = Join-Path $bundleDir "open890-pid-check.log"
  cmd.exe /c "`"$RootDir\bin\open890.bat`" pid" 2>&1 |
    Out-File -FilePath $pidCheckLog -Encoding UTF8

  $dirListing = Join-Path $bundleDir "install-dir-listing.txt"
  Get-ChildItem -Path $RootDir -Force |
    Format-Table Mode, LastWriteTime, Length, Name -AutoSize |
    Out-File -FilePath $dirListing -Encoding UTF8

  $launcherContextPath = Join-Path $bundleDir "launcher-context.txt"
  @(
    "timestamp=$(Get-Date -Format o)",
    "root_dir=$RootDir",
    "url=$Url",
    "timeout_seconds=$TimeoutSeconds",
    "server_log=$serverLog",
    "diagnostics_opt_in_file=$diagnosticsOptInFile",
    "failure_reason=$FailureReason"
  ) | Out-File -FilePath $launcherContextPath -Encoding UTF8

  $installerLogs = Get-LatestInstallerLogs
  foreach ($log in $installerLogs) {
    $dest = Join-Path $bundleDir ("installer-" + $log.Name)
    Copy-Item -Path $log.FullName -Destination $dest -Force
  }

  $eventLogPath = Join-Path $bundleDir "windows-application-events.txt"
  Get-WinEvent -LogName Application -MaxEvents 500 -ErrorAction SilentlyContinue |
    Where-Object { $_.Message -match 'open890|beam|erlang|vcruntime|ucrtbase' } |
    Select-Object TimeCreated, ProviderName, Id, LevelDisplayName, Message |
    Format-List |
    Out-File -FilePath $eventLogPath -Encoding UTF8

  if (Test-Path $zipPath) {
    Remove-Item -Path $zipPath -Force
  }

  try {
    Compress-Archive -Path (Join-Path $bundleDir "*") -DestinationPath $zipPath -Force
  } catch {
    $zipPath = $null
  }

  return @{
    BundleDir = $bundleDir
    ZipPath = $zipPath
  }
}

function Open-PreFilledGitHubIssue {
  param(
    [string]$FailureReason,
    [string]$AttachmentHint
  )

  $title = [System.Uri]::EscapeDataString("Windows installer: open890 failed to start")

  $bodyText = @"
## Summary
open890 was installed with diagnostics opt-in enabled, but failed to start from the Windows launcher.

## Failure reason
$FailureReason

## Environment
- Windows version: <fill in>
- open890 version: <fill in>
- Installer filename: <fill in>

## Logs
Attach the diagnostics archive generated by the launcher:
$AttachmentHint

## Reproduction steps
1. Install open890 using the Windows installer.
2. Launch open890 from desktop/start menu.
3. Observe startup failure.

## Additional notes
<optional>
"@

  $body = [System.Uri]::EscapeDataString($bodyText)
  $issueUrl = "$githubIssueBaseUrl?title=$title&body=$body"
  Start-Process $issueUrl
}

$ready = Test-Open890Ready -Endpoint $Url

if (-not $ready) {
  $startCommand = "`"$RootDir\bin\open890.bat`" start > `"$serverLog`" 2>&1"
  Start-Process -FilePath "cmd.exe" -ArgumentList "/c $startCommand" -WindowStyle Minimized
}

for ($i = 0; $i -lt $TimeoutSeconds; $i++) {
  if (Test-Open890Ready -Endpoint $Url) {
    $ready = $true
    break
  }
  Start-Sleep -Seconds 1
}

Start-Process $Url

Add-Type -AssemblyName PresentationFramework

if ($ready) {
  [void][System.Windows.MessageBox]::Show(
    "open890 is active.`n`nYour browser will open at $Url",
    "open890"
  )
} else {
  $failureReason = "Launcher timeout after $TimeoutSeconds seconds waiting for $Url"
  $diagnosticsEnabled = Test-Path $diagnosticsOptInFile

  if ($diagnosticsEnabled) {
    $bundle = New-Open890DiagnosticsBundle -FailureReason $failureReason

    if ($bundle.ZipPath) {
      Open-PreFilledGitHubIssue -FailureReason $failureReason -AttachmentHint $bundle.ZipPath
      Start-Process "explorer.exe" "/select,`"$($bundle.ZipPath)`""

      [void][System.Windows.MessageBox]::Show(
        "open890 did not become ready.`n`nA diagnostics bundle was created:`n$($bundle.ZipPath)`n`nA pre-filled GitHub issue draft has been opened. Please attach the zip file before submitting.",
        "open890"
      )
    } else {
      Open-PreFilledGitHubIssue -FailureReason $failureReason -AttachmentHint $bundle.BundleDir
      Start-Process "explorer.exe" "`"$($bundle.BundleDir)`""

      [void][System.Windows.MessageBox]::Show(
        "open890 did not become ready.`n`nDiagnostics were collected in:`n$($bundle.BundleDir)`n`nA pre-filled GitHub issue draft has been opened.",
        "open890"
      )
    }
  } else {
    [void][System.Windows.MessageBox]::Show(
      "open890 is starting.`n`nPlease open your browser to $Url if it does not open automatically.`n`nIf startup fails, check: $serverLog",
      "open890"
    )
  }
}

exit 0
